artifacts:
  FACERECOG_MODEL: deepface
  HAARCASCADE_PATH: "data\\models\\haarcascade_frontalface_default.xml"
  INTERMIDEIATE_DIR: "data\\Data2"
  CONTOUR_FILE: "contour_id.jpg"
  FACE_IMG1: "data\\Data2\\extracted_face.jpg"
  FACE_IMG2: "data\\Data2\\face_image.jpg"
